version: 2.1

jobs:
  run:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: echo "Test of CircleCI run job executed"

workflows:
  build_and_test:
    jobs:
      - run
